In [2]:
import torch
test = torch.tensor([1, 2])
print(test)

tensor([1, 2])


In [8]:
a = torch.zeros((3, 4))
a.add(7)

tensor([[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]])

In [5]:
torch.randint(0, 10, (3, 4))

tensor([[3, 5, 4, 9],
        [9, 8, 7, 7],
        [3, 5, 8, 8]])

In [6]:
torch.rand(3, 4)

tensor([[0.4011, 0.3697, 0.4983, 0.5558],
        [0.6163, 0.3128, 0.4982, 0.8171],
        [0.8886, 0.5422, 0.9265, 0.3059]])

In [7]:
import numpy as np
x = np.array([1, 2, 3])
y = torch.tensor(x)
print(type(x), type(y))

<class 'numpy.ndarray'> <class 'torch.Tensor'>


In [10]:
u = torch.tensor([1.0, 2.0, 3.0])
v = u.view(3, 1)
u, v

(tensor([1., 2., 3.]),
 tensor([[1.],
         [2.],
         [3.]]))

In [18]:
# gradient tracking
xx = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
print(xx)  # None

tensor([1., 2., 3.], requires_grad=True)


In [19]:
out = xx.pow(3).sum()
out.backward()
print(xx.grad)  # gradient

tensor([ 3., 12., 27.])
